fixed several issues related to https://github.com/ihashacks/nagios/issues/1 misc cleanup

diff --git a/check_dell_warranty b/check_dell_warranty
--- a/check_dell_warranty
+++ b/check_dell_warranty
@@ -4,7 +4,7 @@
 #	License
 ################################################################################
 #
-#	Copyright (c) 2008, 2011 Brandon Pierce <brandon@ihashacks.com>
+#	Copyright (c) 2008, 2011, 2012 Brandon Pierce <brandon@ihashacks.com>
 #
 #	This program is free software: you can redistribute it and/or modify
 #	it under the terms of the GNU General Public License as published by
@@ -41,45 +41,50 @@
 #		Added timeout options to lynx to hopefully resolve false positive
 #		when the Dell site is slow to respond.
 #
+#	Updated 20120603
+#
+#		Overhaul this damn thing to work with Dell's re-done support site.
+#		Added exit case when invalid service tag is input or some other
+#		failure occurs.
+#
 
-# Uncomment for debugging
-#set -x
-
-GET="lynx -connect_timeout=30 -read_timeout=30 -source"
+GET="lynx -connect_timeout=30 -read_timeout=30 -dump -nocolor -nolist"
 DURL="http://support.dell.com/support/topics/global.aspx/support/my_systems_info/details?c=us&l=en&s=gen&servicetag="
 SVCTAG=$1
 DWARN=$2
 DCRIT=$3
 
+# help
 usage()
 {
 	echo "Usage: `basename $0` <service tag> <warning days> <critical days>"
 	exit 1
 }
 
+# require exactly 3 parameters
 if [ ${#@} -ne 3 ] ; then
 	usage
 fi
 
+# retrieve the Dell warranty with most remaining days
 DAYSLEFT=`$GET "$DURL$SVCTAG" | \
-	grep contract_table | \
-	grep -o -E ">[0-9]{1,3}<"`
+	grep -m 1 -o '\[[0-9]*\]' |\
+	sed -e 's/\[// ; s/\]//'`
 
-INTDAYS=`echo "$DAYSLEFT" | sed -e ' s/>// ; s/<// ' | uniq | sort -rn | head -n 1`
-
-#
-# Test it
-#
-if [ $INTDAYS -le "0" ]; then
+# test it
+if [ ! -n "$DAYSLEFT" ]; then
+	echo "Unable to verify the Service Tag"
+	exit 3
+elif [ $DAYSLEFT -le "0" ]; then
 	echo "Warranty has expired for <a href=$DURL$SVCTAG>$SVCTAG</a>"
 	exit 2
-elif [ $INTDAYS -le $DCRIT ]; then
-	echo "Warranty expires in $INTDAYS days for <a href=$DURL$SVCTAG>$SVCTAG</a>"
+elif [ $DAYSLEFT -le $DCRIT ]; then
+	echo "Warranty expires in $DAYSLEFT days for <a href=$DURL$SVCTAG>$SVCTAG</a>"
 	exit 2
-elif [ $INTDAYS -le $DWARN ]; then
-	echo "Warranty expires in $INTDAYS days for <a href=$DURL$SVCTAG>$SVCTAG</a>"
+elif [ $DAYSLEFT -le $DWARN ]; then
+	echo "Warranty expires in $DAYSLEFT days for <a href=$DURL$SVCTAG>$SVCTAG</a>"
 	exit 1
 else
-	echo "Warranty expires in $INTDAYS days for <a href=$DURL$SVCTAG>$SVCTAG</a>"
+	echo "Warranty expires in $DAYSLEFT days for <a href=$DURL$SVCTAG>$SVCTAG</a>"
 	exit 0
 fi
